server:
  port: 8001

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  profiles:
    active:
      - default

  datasource:
    url: jdbc:h2:mem:order
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        sql_comments: true

logging:
  level:
    org.hibernate.type: trace

feign:
#  accounts-api:
#    name: accounts-api
#    url: http://localhost:8001
#  products-api:
#    name: products-api
#    url: http://localhost:8002
#  carts-api:
#    name: carts-api
#    url: http://localhost:8003

  mock-api:
    name: mock-api
    url: http://localhost:8000